export const vendorHeaders: string[] = [
  "id",
  "usageCount",
  "createdAt",
  "updatedAt",
  "name",
  "customerId",
  "requestorId",
  "baseURL",
  "apiKey",
  "platform",
  "provider",
  "startingYear",
  "notes",
  "requireIpChecking",
  "requireTwoAttemptsPerReport",
  "requireRequestsThrottled",
];

export const REPORTS = {
  PR: "Platform Report",
  TR: "Title Report",
  DR: "Database Report",
  IR: "Item Report",
  PR_P1: "Platform Usage",
  DR_D1: "Database Search and Item Usage",
  DR_D2: "Database Access Denied",
  TR_B1: "Book Requests (controlled)",
  TR_B2: "Book Access Denied",
  TR_B3: "Book Usage by Access Type",
  TR_J1: "Journal Requests (Controlled)",
  TR_J2: "Journal Access Denied",
  TR_J3: "Journal Usage by Access Type",
  TR_J4: "Journal Requests by YOP (Controlled)",
  IR_A1: "Journal Article Requests",
  IR_M1: "Multimedia Item Requests",
};

export const dataVersions = {
  data5_0: "data5_0",
  data5_1: "data5_1",
} as const;

export const reportsIds = [
  "TR",
  "DR",
  "IR",
  "PR",
  "TR_B1",
  "TR_B2",
  "TR_B3",
  "TR_J1",
  "TR_J2",
  "TR_J3",
  "TR_J4",
  "IR_A1",
  "IR_M1",
  "DR_D1",
  "DR_D2",
  "PR_P1",
];
